### ISSUE TITLE
branch rest/dev

### ISSUE THREAD

**Issue by hyde777** [alex-lairan/SimpleAuthJava#10]
Hey guys,

Are you using the branch rest/dev ?

feel like it's just a typo so maybe we should delete it

**Comment by TristanEduProjet** [comment]
t'inquiète, c'est ma branche qui est mal orthographiée (erreur de frappe)
je corrige ça

**Comment by TristanEduProjet** [comment]
il y a une branche `rest/dev` et une autre `reset/dev` ...
je regarde ça et je fais place net

**Comment by TristanEduProjet** [comment]
J'ai comparer l'historique des 2 branches, c'est bien une erreur de ma part, il faut de je renomme ma branche.

**Comment by TristanEduProjet** [comment]
C'est corrigé
